northwind:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgresql-csdataanalytics.alwaysdata.net
      port: 5432
      user: csdataanalytics
      password: rio@2023
      database: csdataanalytics_db
      schema: dw  # Adicione esta linha para especificar o esquema