version: 2

sources:
  - name: northwind
    description: This is a replica of the Postgres database used by our client.
    tables:
      - name: orders
        description: >
          One record per order. Includes cancelled and deleted orders.
        columns:
          - name: order_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
      - name: products
        description: This table contains information about Northwind products.
      - name: shippers
        description: This table contains information about Northwind shippers.
      - name: employees
        description: This table contains information about Northwind employees.
      - name: customers
        description: This table contains information about Northwind customers
      - name: suppliers    
        description: This table contains information about Northwind suppliers.  
      - name: order_details    
        description: This table contains information about Northwind order_details.     